// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Car: typeof import('./src/components/leftBox/car.vue')['default']
    CarCard: typeof import('./src/components/leftBox/carCard.vue')['default']
    Card: typeof import('./src/components/leftBox/card.vue')['default']
    CarList: typeof import('./src/components/leftBox/carList.vue')['default']
    ComButton: typeof import('./src/components/comButton/index.vue')['default']
    Confirm: typeof import('./src/components/dialog/confirm.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    GoodsCard: typeof import('./src/components/rightBox/goodsCard.vue')['default']
    GoodsList: typeof import('./src/components/rightBox/goodsList.vue')['default']
    HeaderLeft: typeof import('./src/components/header/headerLeft.vue')['default']
    HeaderRight: typeof import('./src/components/header/headerRight.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Nulldata: typeof import('./src/components/nulldata/index.vue')['default']
    Orderdatils: typeof import('./src/components/rightBox/orderdatils.vue')['default']
    OrderDetails: typeof import('./src/components/rightBox/orderDetails.vue')['default']
    OrderList: typeof import('./src/components/leftBox/orderList.vue')['default']
    Refund: typeof import('./src/components/dialog/refund.vue')['default']
    ResultStatus: typeof import('./src/components/dialog/resultStatus.vue')['default']
    ReturnGoods: typeof import('./src/components/dialog/returnGoods.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sku: typeof import('./src/components/dialog/sku.vue')['default']
    Specs: typeof import('./src/components/rightBox/specs.vue')['default']
    TopSearch: typeof import('./src/components/rightBox/topSearch.vue')['default']
  }
}
